---
title: "Graph Parsed USDA Food Data"
author: "Victor Jacobson"
date: "March 21, 2017"
output: html_document
---

#Use parsed USDA Food Data
```{r}
library(ggplot2)
library(plotly)
load("USDA_Parsed.Rdata")

#Show Cholesterol by Food Categories & Preparation
#data <-
  ggplot(USDA_Parsed, aes(x = category, y = Cholestrl_.mg., label = Shrt_Desc)) + 
  geom_boxplot(aes(fill = category), outlier.shape = NA) + 
  #scale_fill_manual(values = c("Grey", "#F7C96F", "#FFF7D6", "#6E72A1", "#AA8844", "#EEBB88", "#FFEEDD"), guide = FALSE ) +
  geom_point(aes(x = category, y = Cholestrl_.mg., color = prep), 
             position = position_jitterdodge(dodge.width = 0.75), alpha = .75, size = 2) + 
  scale_color_manual(values = c("#999999", "#FF2266", "#663300"), name = "Preparation") + 
  coord_cartesian(ylim = c(0, 160)) + 
  labs(title = "Cholesterol by Category & Preparation", x = "Category", y = "Cholesterol (mg)") +
  theme(text = element_text(size = 20), plot.title = element_text(hjust = 0.5),
        legend.position = c(.3, .87))
ggplotly(data, tooltip = c("Shrt_Desc", "Cholestrl_.mg."))
#ggsave("visuals/CholCatPrepMain.png", plot = data, device = NULL, path = NULL, scale = 1, width = 12, height = 9, units = "in", dpi = 600, limitsize = TRUE)
```



#Show Meats & Pultry
```{r}
meats_poultry <- USDA_Parsed[grepl("Meat|Poultry", USDA_Parsed$category),]

# order food factors by median
library(dplyr)
mpfactor_list <- meats_poultry %>% group_by(food)  %>% summarise(chol_median = median(Cholestrl_.mg., na.rm=TRUE))
mpfactor_list <- mpfactor_list[order(mpfactor_list$chol_median),]
#utils::View(mpfactor_list)
meats_poultry$food <- factor(meats_poultry$food, levels = mpfactor_list$food)

ggplot(meats_poultry, aes(x = food, y = Cholestrl_.mg., label = Shrt_Desc)) + 
  facet_grid(.~category, space = "free", scales = "free") + 
  geom_boxplot(aes(fill = food), outlier.shape = NA) + 
  scale_fill_brewer(palette = "Set3", guide = FALSE) + 
  geom_point(aes(x = food, y = Cholestrl_.mg., color = prep), 
             position = position_jitterdodge(dodge.width = 0.75), alpha = .75, size = 2) + 
  scale_color_manual(values = c("#999999", "#FF2266", "#663300"), name = "Preparation") + 
  coord_cartesian(ylim = c(25, 160)) + 
  labs(title = "Cholesterol in Meats & Poultry by Preparation", x = "", y = "Cholesterol (mg)") +
  theme(text = element_text(size = 15), plot.title = element_text(hjust = 0.5),
        legend.position = c(.83, .16))
ggsave("visuals/CholMeatPultryPrep.png", device = NULL, path = NULL, scale = 1, width = 9, height = 5, units = "in", dpi = 600, limitsize = TRUE)
#ggplotly(data, tooltip = c("Shrt_Desc", "Cholestrl_.mg."))

```

#Breakdown all categories
```{r}
library(dplyr)
library(ggplot2)

all_data <- USDA_Parsed

# order food factors by median
mpfactor_list <- all_data %>% group_by(food)  %>% summarise(chol_median = median(Cholestrl_.mg., na.rm=TRUE))
mpfactor_list <- mpfactor_list[order(mpfactor_list$chol_median),]
#utils::View(mpfactor_list)
all_data$subcat <- factor(all_data$food, levels = mpfactor_list$food)

chol_list <- mpfactor_list %>% filter(chol_median > 20)

all_data <- all_data %>% filter(food %in% chol_list$food)

ggplot(all_data, aes(x = food, y = Cholestrl_.mg., label = Shrt_Desc)) + 
  facet_grid(.~category, space = "free", scales = "free") + 
  geom_boxplot(aes(fill = food), outlier.shape = NA) + 
  scale_fill_discrete(guide = FALSE) + 
  geom_point(aes(x = food, y = Cholestrl_.mg., color = prep), 
             position = position_jitterdodge(dodge.width = 0.75), alpha = .75, size = 2) + 
  scale_color_manual(values = c("#999999", "#FF2266", "#663300"), name = "Preparation") + 
  coord_cartesian(ylim = c(0, 160)) + 
  labs(title = "Cholesterol by Meats, Poultry & Preparation", x = "", y = "Cholesterol (mg)") +
  theme(text = element_text(size = 18), plot.title = element_text(hjust = 0.5))
ggsave("visuals/CholCatFoodPrep.png", device = NULL, path = NULL, scale = 1, width = 18, height = 7, units = "in", dpi = 600, limitsize = TRUE)
#ggplotly(data, tooltip = c("Shrt_Desc", "Cholestrl_.mg."))

```
#Breakdown all categories2
```{r}
library(dplyr)
library(ggplot2)

all_data <- USDA_Parsed

# order food factors by median
mpfactor_list <- all_data %>% group_by(food)  %>% summarise(chol_median = median(Cholestrl_.mg., na.rm=TRUE))
mpfactor_list <- mpfactor_list[order(mpfactor_list$chol_median),]
#utils::View(mpfactor_list)
all_data$subcat <- factor(all_data$food, levels = mpfactor_list$food)

chol_list <- mpfactor_list %>% filter(chol_median > 20)

all_data <- all_data %>% filter(food %in% chol_list$food)

ggplot(all_data, aes(x = food, y = Cholestrl_.mg., label = Shrt_Desc)) + 
  facet_grid(.~category, space = "free", scales = "free") + 
  geom_boxplot(aes(fill = food), outlier.shape = NA) + 
  scale_fill_discrete(guide = FALSE) + 
  geom_point(aes(x = food, y = Cholestrl_.mg., color = prep), 
             position = position_jitterdodge(dodge.width = 0.75), alpha = .75, size = 2) + 
  scale_color_manual(values = c("#999999", "#FF2266", "#663300"), name = "Preparation") + 
  coord_cartesian(ylim = c(0, 160)) + 
  labs(title = "Cholesterol by Meats, Poultry & Preparation", x = "", y = "Cholesterol (mg)") +
  theme(text = element_text(size = 18), plot.title = element_text(hjust = 0.5))
ggsave("visuals/CholCatFoodPrep02.png", device = NULL, path = NULL, scale = 1, width = 18, height = 7, units = "in", dpi = 600, limitsize = TRUE)
#ggplotly(data, tooltip = c("Shrt_Desc", "Cholestrl_.mg."))

```
#liverEggsBrain


```{r}
#beef <- USDA_Parsed[grepl("Beef", USDA_Parsed$food),]
liverEggsBrain <- USDA_Parsed[grepl("Liver|Eggs|Brain", USDA_Parsed$food),]
liverEggsBrain <- liverEggsBrain[!grepl(" / ", liverEggsBrain$food),]#remove hybrids
liverEggsBrain$food <- factor(liverEggsBrain$food, levels = c("Liver", "Eggs", "Brain"))
ggplot(liverEggsBrain, aes(x = food, y = Cholestrl_.mg., color = prep))+ 
  geom_point(position = position_jitterdodge(dodge.width = 0.75)) + 
  scale_color_manual(values = c("#999999", "#FF2266", "#663300"), name = "Preparation") + 
  #coord_cartesian(ylim = c(0, 160)) + 
  #Add line to show recommended daily value
  geom_hline(yintercept = 300, color = "Red",linetype = "dashed") +
  labs(title = "Highest Cholesterol Foods by Preparation", x = "", y = "Cholesterol(mg)") +
  theme(text = element_text(size = 10), plot.title = element_text(hjust = 0.5),
        legend.position = c(.15, .7))
ggsave("visuals/CholLiverEggsBrainPrep.png", device = NULL, path = NULL, scale = 1, width = 4, height = 3.5, units = "in", dpi = 600, limitsize = TRUE)

egg <- USDA_Parsed[grepl("Eggs", USDA_Parsed$food),]

```


#Histogram
```{r}
# Basic
ggplot(USDA_Parsed, aes(Cholestrl_.mg.)) +
  geom_histogram(binwidth = 10)+
  labs(title = "Cholesterol Distribution", x = "Cholesterol (mg)", y = "Count") 
ggsave("visuals/CholHistBasic.png", scale = 2, width = 3, height = 2, units = "in", dpi = 600, limitsize = TRUE)

# Zoomed In
ggplot(USDA_Parsed, aes(Cholestrl_.mg.)) +
  geom_histogram(binwidth = 5) +
  coord_cartesian(xlim = c(0, 260)) + 
  labs(title = "Cholesterol Distribution", x = "Cholesterol (mg)", y = "Count")  +
  theme(text = element_text(size = 10), plot.title = element_text(hjust = 0.5))
ggsave("visuals/CholHistZoom.png", scale = 2, width = 3, height = 2, units = "in", dpi = 600, limitsize = TRUE)


# Zoomed In More
ggplot(USDA_Parsed, aes(Cholestrl_.mg.)) +
  geom_histogram(binwidth = 5) +
  coord_cartesian(xlim = c(20, 140), ylim = c(0, 300)) +
  labs(title = "Cholesterol Distribution Zoom In", x = "Cholesterol (mg)", y = "Count") +
  theme(text = element_text(size = 10), plot.title = element_text(hjust = 0.5))
ggsave("visuals/CholHistZoomMore.png", scale = 2, width = 3, height = 2, units = "in", dpi = 600, limitsize = TRUE)


# Scale 
ggplot(USDA_Parsed, aes(Cholestrl_.mg., fill = category)) +
  geom_histogram(binwidth = 5) +
  coord_cartesian(xlim = c(20, 140), ylim = c(0, 300)) +
  scale_fill_brewer(palette = "Accent") +
  labs(title = "Cholesterol Distributed by Category", x = "Cholesterol (mg)", y = "Count") +
  theme(text = element_text(size = 10), plot.title = element_text(hjust = 0.5),
        legend.position = c(.85, .6))
ggsave("visuals/CholHistScaleCat.png", scale = 2, width = 3, height = 2, units = "in", dpi = 600, limitsize = TRUE)


# Scale 
ggplot(USDA_Parsed, aes(Cholestrl_.mg., fill = prep)) +
  geom_histogram(binwidth = 5) +
  coord_cartesian(xlim = c(20, 140), ylim = c(0, 300))+ 
  scale_fill_manual(values = c("#999999", "#FF2266", "#663300"), name = "Preparation") +
  labs(title = "Cholesterol Distributed by Preparation", x = "Cholesterol (mg)", y = "Count") +
  theme(text = element_text(size = 10), plot.title = element_text(hjust = 0.5),
        legend.position = c(.85, .6))
ggsave("visuals/CholHistScalePrep.png", scale = 2, width = 3, height = 2, units = "in", dpi = 600, limitsize = TRUE)

```


#Word Cloud
```{r}
library(tm)
library(SnowballC)
library(wordcloud)
library(stringr)
  
# remove punctuation and stopwords (the, a, etc...)
# cholCorpus <- tm_map(cholCorpus, replacePunctuation)
# cholCorpus <- tm_map(cholCorpus, removeWords, stopwords('english'))
load("USDA16.Rdata")
USDA_Corpus <- USDA16$Shrt_Desc

USDA_Corpus <- str_to_lower(USDA_Corpus)
USDA_Corpus <- gsub(" ", "-", USDA_Corpus)
USDA_Corpus <- gsub(",", " ", USDA_Corpus)
#USDA_Corpus <- str_replace_all(USDA_Corpus, "ckd", " ")
#USDA_Corpus <- str_replace_all(USDA_Corpus, "raw", " ")

# create a corpus and simplify text
USDA_Corpus <- Corpus(VectorSource(USDA_Corpus))
USDA_Corpus <- tm_map(USDA_Corpus, PlainTextDocument)

# stemming - reduce all words to root words
# cholCorpus <- tm_map(cholCorpus, stemDocument)

# Wordcloud of everything 
png(filename = "visuals/WordCloudUSDA.png",
    width = 600, height = 600, units = "px")
wordcloud(USDA_Corpus, scale = c(8, 1), max.words = 150, random.order = FALSE, random.color = TRUE)


# Wordcloud of First Words 
USDA_Corpus <- word(short_desc)
png(filename = "visuals/WordCloudFirstWords.png",
    width = 600, height = 600, units = "px")
wordcloud(USDA_Corpus, scale = c(8, 1), max.words = 150, random.order = FALSE, random.color = TRUE)


# Test using different frequency
wordcloud(mpfactor_list$food, freq = mpfactor_list$chol_median,
          scale = c(4, .1), 
          max.words = 100, random.order = FALSE, random.color = TRUE)

#Create new list using first word

# Reduce shortdesc to first word only
ShrtDesc <- USDA16$Shrt_Desc
ShrtDesc <- str_to_lower(ShrtDesc)
ShrtDesc <- gsub("-", " ", ShrtDesc)
ShrtDesc <- gsub(",", " ", ShrtDesc)
ShrtDesc <- gsub(".*brain.*", "brain", ShrtDesc)
ShrtDesc <- gsub(".*liver.*", "liver", ShrtDesc)
ShrtDesc <- word(ShrtDesc)
#wordcloud(ShrtDesc, max.words = 100, random.order = FALSE, random.color = TRUE)

USDACholCorpus <- data.frame(ShrtDesc, Cholesterol = USDA16$Cholestrl_.mg.)
USDACholCorpus <- USDACholCorpus[!is.na(USDACholCorpus$Cholesterol),]#Remove NA

USDACholCorpus <- USDACholCorpus %>% group_by(ShrtDesc) %>% 
                  summarise(Chol_mean = round(mean(Cholesterol, na.rm = TRUE), digits = 0), 
                            Freq = n(), Chol_rel = round(sqrt(Freq + 5) * sqrt(Chol_mean+50), digits = 0))

USDACholCorpus <- filter(USDACholCorpus, Chol_mean >= 40)#Remove Low Cholesterol


# Size reflects mean cholesterol
png(filename = "visuals/WordCloudCholMean.png",
    width = 560, height = 560, units = "px")
wordcloud(USDACholCorpus$ShrtDesc, freq = USDACholCorpus$Chol_mean,
          scale = c(8, 1),
          max.words = 150, random.order = FALSE, random.color = TRUE)



# Size reflects Relevance

# Add the word 'Cholesterol' to the word cloud
#USDACholCorpus <- rbind(USDACholCorpus, c("Cholesterol",0,0, 800))
#USDACholCorpus <- data.frame(USDACholCorpus[,1] , Chol_rel = as.numeric(USDACholCorpus[,4]))
#USDACholCorpus[nrows(USDACholCorpus) + 1,] <- c("Cholesterol",0,0, 800)
#add_row(USDA_Corpus, ShrtDesc = "Cholesterol", Chol_mean = 0, Freq = 0, Chol_rel = 800)
c = data.frame(ShrtDesc = "cholesterol", Chol_mean = 0, Freq = 0, Chol_rel = 450)

USDACholCorpus <- bind_rows(USDACholCorpus, c)

png(filename = "visuals/WordCloudCholesterelevance.png",
    width = 1200, height = 1200, units = "px")
wordcloud(USDACholCorpus$ShrtDesc, freq = USDACholCorpus$Chol_rel,
          scale = c(11, 2), colors = pal2,
          max.words = 200, random.order = FALSE, random.color = TRUE)

pal2 <- brewer.pal(8,"Dark2")

```



#CorrPlot
```{r}
library(corrplot)

remNonNum <- function(data){
  data <- data[,sapply(data, is.numeric)]
  data[is.na(data)] <-0
  return(data)
}

corIsoParams <- function(data, param, corr){
  data <- remNonNum(data)
  dataCorr <- cor(data, method = "pearson",use = "complete")
  dataCorr <- data.frame(dataCorr)
  if(corr < 1){
    dataCorr <- subset( dataCorr, dataCorr[,param] >= corr | dataCorr[,param] <= -corr)
    dataCorr <- rownames(dataCorr)
  } else {
    dataCorr <- dataCorr[sort.list(abs(dataCorr[,param]), decreasing = TRUE)]
    dataCorr <- dataCorr[,1:corr]
    dataCorr <- colnames(dataCorr)
  }
  data <- data[ ,dataCorr]
  data <- cor(data, method = "pearson",use = "complete")
  return(data)
}

# Extract data
USDA_Corrplot <- USDA_Parsed # Use all

# Remove non-numeric
USDA_Numeric <- remNonNum(USDA_Corrplot)

#Corrplot of all Data and Parameters
#corrplot_all <- cor(USDA_Numeric, method = "pearson",use = "complete")
corrplot_all <- corIsoParams(USDA_Corrplot, 'Cholestrl_.mg.', 25)
png(filename = "visuals/CorrPlot_25.png",
    width = 1000, height = 1000, units = "px")
corrplot(corrplot_all, type = "upper", order = "hclust", tl.col = "black", tl.srt = 45, 
         number.font = 1)

#Isolate parameters with 0.2 correlation or higher
corr_0_2 <- corIsoParams(USDA_Parsed, 'Cholestrl_.mg.', 25)

png(filename = "visuals/CorrPlot_HighChol_25.png",
    width = 1000, height = 1000, units = "px")
corrplot(corr_0_2, type = "upper", order = "hclust", tl.col = "black", tl.srt = 45)



#Correlation of top 25 for Items with High Cholesterol
corr_highchol_02 <- subset(USDA_Parsed, Cholestrl_.mg. >= 40)

corr_highchol_02 <- corIsoParams(corr_highchol_02, 'Cholestrl_.mg.', 25)

png(filename = "visuals/CorrPlot_Chol_25.png",
    width = 1000, height = 1000, units = "px")
corrplot(corr_highchol_02, type = "upper", order = "hclust", tl.col = "black", tl.srt = 45, 
         number.font = 1)


#Correlation Top 25 for Beef
corr_beef <- subset(USDA_Parsed, food == "Beef")

corr_beef <- corIsoParams(corr_beef, 'Cholestrl_.mg.', 25)


png(filename = "visuals/CorrPlot_Beef_Chol_25.png",
    width = 1000, height = 1000, units = "px")
corrplot(corr_beef, type = "upper", order = "hclust", tl.col = "black", tl.srt = 45, 
         number.font = 1)

#Correlation Top 25 for Chicken
corr_chkn_10 <- subset(USDA_Parsed, food == "Chicken")

corr_chkn_10 <- corIsoParams(corr_chkn_10, 'Cholestrl_.mg.', 25)
#corr_chkn_10 <- cor(remNonNum(corr_chkn_10),  method = "pearson",use = "complete")

png(filename = "visuals/CorrPlot_Chkn_Chol_25.png",
    width = 1000, height = 1000, units = "px")
corrplot(corr_chkn_10, type = "upper", order = "hclust", tl.col = "black", tl.srt = 45, 
         number.font = 1)


#Correlation Top 25 for Raw
corr_raw <- subset(USDA_Parsed, prep == "raw")

corr_raw <- corIsoParams(corr_raw, 'Cholestrl_.mg.', 25)
#corr_chkn_10 <- cor(remNonNum(corr_chkn_10),  method = "pearson",use = "complete")

png(filename = "visuals/CorrPlot_Raw_25.png",
    width = 1000, height = 1000, units = "px")
corrplot(corr_raw, type = "upper", order = "hclust", tl.col = "black", tl.srt = 45, 
         number.font = 1)


#Correlation Top 25 for Cooked
corr_cooked <- subset(USDA_Parsed, prep == "cooked")

corr_cooked <- corIsoParams(corr_cooked, 'Cholestrl_.mg.', 25)
#corr_chkn_10 <- cor(remNonNum(corr_chkn_10),  method = "pearson",use = "complete")

png(filename = "visuals/CorrPlot_Cooked_25.png",
    width = 1000, height = 1000, units = "px")
corrplot(corr_cooked, type = "upper", order = "hclust", tl.col = "black", tl.srt = 45, 
         number.font = 1)


#Correlation Top 25 for Seafood
corr_seafood <- subset(USDA_Parsed, subcat == "Seafood")

corr_seafood <- corIsoParams(corr_seafood, 'Cholestrl_.mg.', 25)
#corr_chkn_10 <- cor(remNonNum(corr_chkn_10),  method = "pearson",use = "complete")

png(filename = "visuals/CorrPlot_Seafood_test.png",
    width = 1000, height = 1000, units = "px", bg = "black")
corrplot(corr_seafood, type = "upper", order = "hclust", tl.col = "black", tl.srt = 45, 
         number.font = 1)

# Beef Chol corr plot top 5
library(reshape)
USDA_Beef <- subset(USDA_Parsed, food == "Beef")

corr_beef <- corIsoParams(USDA_Beef, 'Cholestrl_.mg.', 5)
corr_chol_beef <- rownames(corr_beef)
USDA_Beef <- USDA_Beef[,corr_chol_beef]
USDA_Beef <- melt(USDA_Beef, id = "Cholestrl_.mg.")

ggplot(USDA_Beef, aes(x = Cholestrl_.mg., y = value, color = variable)) +
  geom_point()


# Beef Plot Chol vs Highest Correlation
USDA_CorrParam <- subset(USDA_Parsed, food == "Chicken")

corr_param <- corIsoParams(USDA_CorrParam, 'Cholestrl_.mg.', 5)
corr_param <- rownames(corr_param)
USDA_CorrParam <- USDA_CorrParam[,c(corr_param)]
USDA_CorrParam <- melt(USDA_CorrParam, id = "Cholestrl_.mg.")

ggplot(USDA_CorrParam, aes(x = Cholestrl_.mg., y = value, color = variable)) +
  geom_point() + coord_cartesian(xlim = c(0,250), ylim = c(0,50))


dev.off()
```

#Plot CHol vs Prot Cooked Raw
```{r}
library(dplyr)
library(ggplot2)

other = "#666666"
raw =  "#FF2266"
cooked = "#663300"
col_prep <- c(other, raw, cooked)


USDA_Parsed %>%
  #filter(prep != "other") %>%
  filter(category == "PROTEIN FOODS") %>%
  #filter(subcat != "Eggs") %>%
  ggplot(aes(x = Cholestrl_.mg., y = Protein_.g., color = prep)) +
    facet_wrap(~subcat, strip.position = "bottom") + 
    geom_point(position = position_jitter(width = 1),
               size = 2, alpha = .75) +
    coord_cartesian(xlim = c(0,160), ylim = c(0,40)) + 
    scale_color_manual(values = c(other, raw, cooked), name = "Prep") +
    labs(title = "Protein vs Cholesterol, Cooked vs Raw", x = "Cholesterol(mg)", y = "Protein(g)") +
    theme(plot.title = element_text(hjust = .5),
          text = element_text(size = 16))
 ggsave("visuals/Point_CholProt_Prep_FacetSubcat.png", scale = 2, width = 6, height = 4, units = "in", dpi = 600, limitsize = TRUE)   

```


#Plot CHol vs Other Cats
```{r}
library(dplyr)
library(ggplot2)
library(plotly)

col_curedmeats = "#a64d79"
col_eggs = "#f1c232"
col_meats = "#a61c00"
col_plantprot = "#38761d"
col_poultry = "#b45f06"
col_seafood = "#3c78d8"
cols_proteinfoods <- c(col_curedmeats, col_eggs, col_meats, col_plantprot, col_poultry, col_seafood)

#graph <- 
  USDA_Parsed %>%
  filter(category == "PROTEIN FOODS") %>% 
  ggplot(aes(x = Cholestrl_.mg., y = Carbohydrt_.g.,
             size = Protein_.g.,
               shape = prep, 
              label = Shrt_Desc
             )) +
    facet_wrap(~subcat, strip.position = "bottom") +
    geom_point(position = position_jitter(width = 1, height = 0.5),
               alpha = .75,
               aes(color = subcat, fill = subcat)) +
    coord_cartesian(xlim = c(0,160), ylim = c(0,40)) + 
    scale_size(range = c(0,8)) + 
    scale_color_manual(values = cols_proteinfoods, name = "Sub-category", guide = FALSE) +
    scale_fill_manual(values = cols_proteinfoods, name = "Sub-category", guide = FALSE) +
    scale_shape_manual(values = c(21, 24, 22)) + 
    labs(title = "Carbohydrates vs Cholesterol in Protein Foods", x = "Cholesterol(mg)", y = "Carbohydrates(g)") +
    theme(plot.title = element_text(hjust = .5))
 
 ggplotly(graph, tooltip = c("Shrt_Desc", "Cholestrl_.mg.", "Protein_.g.", "Carbohydrt_.g."))
  ggsave("visuals/Point_CholCarbProteinPrep.png", scale = 2, width = 6, height = 4, units = "in", dpi = 600, limitsize = TRUE)   

```

# Aggregate previous Graph
```{r}
library(dplyr)
library(ggplot2)
library(plotly)

USDA_Parsed %>%
  filter(category == "PROTEIN FOODS") %>% 
  group_by(subcat, food, prep) %>%
  summarise(chol_mean = mean(Cholestrl_.mg., rm.na = TRUE),
            carb_mean = mean(Carbohydrt_.g., rm.na = TRUE),
            prot_mean = mean(Protein_.g., rm.na = TRUE)) %>%
  ggplot(aes(x = chol_mean, y = carb_mean,
             size = prot_mean,
               shape = prep
             )) +
    geom_point(position = position_jitter(width = 1, height = 0.5),
               alpha = .75,
               aes(color = subcat, fill = subcat)) +
    coord_cartesian(xlim = c(0,145), ylim = c(0,25)) + 
    scale_size(range = c(0,8)) + 
    scale_color_manual(values = cols_proteinfoods, name = "Sub-category") +
    scale_fill_manual(values = cols_proteinfoods, name = "Sub-category") +
    scale_shape_manual(values = c(21, 24, 22)) + 
    labs(title = "Carbohydrates vs Cholesterol in Protein Foods", x = "Cholesterol(mg)", y = "Carbohydrates(g)") +
    theme(plot.title = element_text(hjust = .5))
  ggsave("visuals/Point_CholCarbProteinPrep_Aggregated.png", scale = 2, width = 6, height = 4, units = "in", dpi = 600, limitsize = TRUE)   


```
#Plot CHol vs Other Cats try binhex cloud
```{r}
library(dplyr)
library(ggplot2)
library(plotly)

#graph <-  
  USDA_Parsed %>%
  filter(category == "PROTEIN FOODS") %>% 
  ggplot(aes(x = Cholestrl_.mg., y = Carbohydrt_.g.,
              #size = Protein_.g.,
              #shape = prep,
              #label = Shrt_Desc,
              #color = subcat
              fill = subcat
             )) +
    geom_hex(binwidth = c(4,1.5)) +
    coord_cartesian(xlim = c(0,160), ylim = c(0,40)) + 
    #scale_size(range = c(0,8)) + 
    #scale_color_manual(values = cols_proteinfoods, name = "Sub-category") +
    scale_fill_manual(values = cols_proteinfoods, name = "Sub-category") +
    #scale_shape_manual(values = c(21, 24, 22)) + 
    labs(title = "Carbohydrates vs Cholesterol in Protein Foods", x = "Cholesterol(mg)", y = "Carbohydrates(g)") +
    theme(plot.title = element_text(hjust = .5))
 
 #ggplotly(graph, tooltip = c("Shrt_Desc", "Cholestrl_.mg.", "Protein_.g.", "Carbohydrt_.g."))
  ggsave("visuals/Point_CholCarbProteinPrep.png", scale = 2, width = 6, height = 4, units = "in", dpi = 600, limitsize = TRUE)   

  
  
  #facet
    USDA_Parsed %>%
  filter(category == "PROTEIN FOODS") %>% 
  ggplot(aes(x = Cholestrl_.mg., y = Carbohydrt_.g.,
              #size = Protein_.g.,
              #shape = prep,
              #label = Shrt_Desc,
              #color = subcat
              fill = subcat
             )) +
     # facet_wrap(~subcat) +
    geom_hex(binwidth = c(4,1.5)) +
    coord_cartesian(xlim = c(0,160), ylim = c(0,40)) + 
    #scale_size(range = c(0,8)) + 
    #scale_color_manual(values = cols_proteinfoods, name = "Sub-category") +
    scale_fill_manual(values = cols_proteinfoods, name = "Sub-category") +
    #scale_shape_manual(values = c(21, 24, 22)) + 
    labs(title = "Carbohydrates vs Cholesterol in Protein Foods", x = "Cholesterol(mg)", y = "Carbohydrates(g)") +
    theme(plot.title = element_text(hjust = .5))
```

#Plot CHol vs Other Cats Facet
```{r}
library(dplyr)
library(ggplot2)
library(plotly)

col_curedmeats = "#a64d79"
col_eggs = "#f1c232"
col_meats = "#a61c00"
col_plantprot = "#38761d"
col_poultry = "#b45f06"
col_seafood = "#3c78d8"
cols_proteinfoods <- c(col_curedmeats, col_eggs, col_meats, col_plantprot, col_poultry, col_seafood)

#graph <- 
  USDA_Parsed %>%
  filter(category == "PROTEIN FOODS") %>% 
  ggplot(aes(x = Cholestrl_.mg., y = Carbohydrt_.g.,
             size = Protein_.g.,
             fill = subcat,
             color = prep, 
             shape = prep,
             label = Shrt_Desc
             )) +
    facet_wrap(~subcat, strip.position = "bottom") +
    geom_point(position = position_jitter(width = 1, height = 0.5),
               alpha = .75) +
    coord_cartesian(xlim = c(0,160), ylim = c(0,40)) + 
    scale_size(range = c(0,8)) + 
    scale_color_manual(values = cols_proteinfoods, name = "Sub-category") +
    scale_fill_manual(values = cols_proteinfoods, name = "Sub-category") +
    scale_shape_manual(values = c(21, 24, 22)) + 
    labs(title = "Carbohydrates vs Cholesterol in Protein Foods", x = "Cholesterol(mg)", y = "Carbohydrates(g)") +
    theme(plot.title = element_text(hjust = .5),
          text = element_text(size = 16))
 
 ggplotly(graph, tooltip = c("Shrt_Desc", "Cholestrl_.mg.", "Protein_.g.", "Carbohydrt_.g."))
  ggsave("visuals/Point_CholCarbProteinPrepFacet.png", scale = 2, width = 6, height = 4, units = "in", dpi = 600, limitsize = TRUE)   

```